import type { LitClock } from './types';

// Full literary clock dataset — every 5-minute slot 00:00–23:55
// Sources: Public domain literature + original prose
const RAW: [string, string, string][] = [
  ["00:00","It was midnight, and tomorrow was the first day of the rest of her life.","— Anonymous"],
  ["00:05","Five minutes past midnight, and the street lay still.","— Anonymous"],
  ["00:10","Ten past midnight — the world asleep, the night alive.","— Anonymous"],
  ["00:15","It was a quarter past midnight when the owl spoke.","— Anonymous"],
  ["00:20","Twenty minutes into the new day, and she was still reading.","— Anonymous"],
  ["00:25","The clock struck twenty-five past the hour of midnight.","— Anonymous"],
  ["00:30","Half past midnight. The fire had burned to embers.","— Anonymous"],
  ["00:35","At thirty-five past midnight, he finally set down the pen.","— Anonymous"],
  ["00:40","Twenty minutes to one in the morning.","— Anonymous"],
  ["00:45","A quarter to one, and the stars were at their brightest.","— Anonymous"],
  ["00:50","Ten minutes to one. She could hear the sea.","— Anonymous"],
  ["00:55","Five to one. The last train had long departed.","— Anonymous"],
  ["01:00","It was one o'clock in the morning and all was still.","— Anonymous"],
  ["01:05","Five past one in the morning — who could sleep?","— Anonymous"],
  ["01:10","The clock showed ten past one when the letter arrived.","— Anonymous"],
  ["01:15","A quarter past one in the still morning.","— Anonymous"],
  ["01:20","Twenty past one — he lit another candle.","— Anonymous"],
  ["01:25","One twenty-five; the notebook remained open.","— Anonymous"],
  ["01:30","Half past one. The house was entirely silent.","— Anonymous"],
  ["01:35","One thirty-five and the rain had not stopped.","— Anonymous"],
  ["01:40","Twenty minutes to two in the morning.","— Anonymous"],
  ["01:45","A quarter to two. She turned the last page.","— Anonymous"],
  ["01:50","Ten to two — the kettle was on.","— Anonymous"],
  ["01:55","Five minutes to two. The stars were fading.","— Anonymous"],
  ["02:00","Two o'clock struck and no one stirred.","— Anonymous"],
  ["02:05","Five past two. The dream began again.","— Anonymous"],
  ["02:10","Ten past two in the morning.","— Anonymous"],
  ["02:15","Quarter past two and still he paced.","— Anonymous"],
  ["02:20","Twenty past two — the ink had dried.","— Anonymous"],
  ["02:25","Two twenty-five. Silence was loudest then.","— Anonymous"],
  ["02:30","Half past two. The moon moved westward.","— Anonymous"],
  ["02:35","Two thirty-five. Not yet dawn.","— Anonymous"],
  ["02:40","Twenty to three in the morning.","— Anonymous"],
  ["02:45","A quarter to three, and the fire was out.","— Anonymous"],
  ["02:50","Ten to three. Sleep would not come.","— Anonymous"],
  ["02:55","Five to three. The world held its breath.","— Anonymous"],
  ["03:00","Three o'clock in the morning. The darkest hour.","— Anonymous"],
  ["03:05","Five past three and the dog barked once.","— Anonymous"],
  ["03:10","Three ten in the morning.","— Anonymous"],
  ["03:15","A quarter past three. She wrote the first sentence.","— Anonymous"],
  ["03:20","Three twenty. The cat watched from the sill.","— Anonymous"],
  ["03:25","Three twenty-five. He had not moved.","— Anonymous"],
  ["03:30","Half past three and the frost was thick.","— Anonymous"],
  ["03:35","Three thirty-five. The stars were countless.","— Anonymous"],
  ["03:40","Twenty to four in the morning.","— Anonymous"],
  ["03:45","A quarter to four. The horizon grayed.","— Anonymous"],
  ["03:50","Ten to four. The first birds stirred.","— Anonymous"],
  ["03:55","Five to four, and the night was nearly done.","— Anonymous"],
  ["04:00","Four o'clock. The bakers were already at work.","— Anonymous"],
  ["04:05","Five past four in the early morning.","— Anonymous"],
  ["04:10","Four ten. The newspaper had not come.","— Anonymous"],
  ["04:15","A quarter past four. The sky lightened faintly.","— Anonymous"],
  ["04:20","Four twenty — the first light crept in.","— Anonymous"],
  ["04:25","Four twenty-five. She put on her coat.","— Anonymous"],
  ["04:30","Half past four. Dawn was close.","— Anonymous"],
  ["04:35","Four thirty-five. Birdsong began.","— Anonymous"],
  ["04:40","Twenty to five. The dew was heavy.","— Anonymous"],
  ["04:45","A quarter to five in the morning.","— Anonymous"],
  ["04:50","Ten to five. She'd been awake all night.","— Anonymous"],
  ["04:55","Five to five. The first train whistled far away.","— Anonymous"],
  ["05:00","Five o'clock in the morning, and the world was new.","— Anonymous"],
  ["05:05","Five past five. The milkman rattled the gate.","— Anonymous"],
  ["05:10","Five ten. A perfect pale sky.","— Anonymous"],
  ["05:15","Quarter past five. The roosters crowed.","— Anonymous"],
  ["05:20","Five twenty. She laced her shoes for the long walk.","— Anonymous"],
  ["05:25","Five twenty-five. Sunrise was minutes away.","— Anonymous"],
  ["05:30","Half past five in the morning.","— Anonymous"],
  ["05:35","Five thirty-five. The frost melted from the glass.","— Anonymous"],
  ["05:40","Twenty to six. The bakery opened its door.","— Anonymous"],
  ["05:45","A quarter to six in the morning.","— Anonymous"],
  ["05:50","Ten to six. She made the first coffee of the day.","— Anonymous"],
  ["05:55","Five to six. She heard the front door open.","— Anonymous"],
  ["06:00","Six o'clock in the morning, and the day had begun.","— Anonymous"],
  ["06:05","Five past six. The street was already busy.","— Anonymous"],
  ["06:10","Six ten in the morning — he checked his watch twice.","— Anonymous"],
  ["06:15","A quarter past six. The kettle sang.","— Anonymous"],
  ["06:20","Six twenty. He read the headlines and frowned.","— Anonymous"],
  ["06:25","Six twenty-five. The school bus had already passed.","— Anonymous"],
  ["06:30","Half past six. She tied her hair and set out.","— Anonymous"],
  ["06:35","Six thirty-five. The world was ordinary and beautiful.","— Anonymous"],
  ["06:40","Twenty to seven. He missed the earlier train.","— Anonymous"],
  ["06:45","A quarter to seven in the morning.","— Anonymous"],
  ["06:50","Ten to seven. The commuters filled the platform.","— Anonymous"],
  ["06:55","Five to seven. Everything was possible.","— Anonymous"],
  ["07:00","Seven o'clock and the city woke all at once.","— Anonymous"],
  ["07:05","Five past seven. He was already late.","— Anonymous"],
  ["07:10","Seven ten. The coffee had gone cold.","— Anonymous"],
  ["07:15","A quarter past seven. The children were eating breakfast.","— Anonymous"],
  ["07:20","Seven twenty. She counted the days until summer.","— Anonymous"],
  ["07:25","Seven twenty-five. The world expected things.","— Anonymous"],
  ["07:30","Half past seven in the morning.","— Anonymous"],
  ["07:35","Seven thirty-five. The radio played an old song.","— Anonymous"],
  ["07:40","Twenty to eight. The emails had already begun.","— Anonymous"],
  ["07:45","A quarter to eight. She revised the plan.","— Anonymous"],
  ["07:50","Ten to eight. The bus was on time for once.","— Anonymous"],
  ["07:55","Five to eight. He rehearsed what he would say.","— Anonymous"],
  ["08:00","Eight o'clock. Another morning, another beginning.","— Anonymous"],
  ["08:05","Five past eight. The doors opened.","— Anonymous"],
  ["08:10","Eight ten. The meeting was not for two hours.","— Anonymous"],
  ["08:15","A quarter past eight. She sharpened her pencil.","— Anonymous"],
  ["08:20","Eight twenty. The light was perfect for working.","— Anonymous"],
  ["08:25","Eight twenty-five. The notebook waited.","— Anonymous"],
  ["08:30","Half past eight. She began.","— Anonymous"],
  ["08:35","Eight thirty-five. He had already filled a page.","— Anonymous"],
  ["08:40","Twenty to nine in the morning.","— Anonymous"],
  ["08:45","A quarter to nine. The work was going well.","— Anonymous"],
  ["08:50","Ten to nine. She saved the document.","— Anonymous"],
  ["08:55","Five to nine. The corridor was quiet.","— Anonymous"],
  ["09:00","Nine o'clock. The morning was still fresh.","— Anonymous"],
  ["09:05","Five past nine. He made a second coffee.","— Anonymous"],
  ["09:10","Nine ten. The post had arrived.","— Anonymous"],
  ["09:15","A quarter past nine. She opened the window.","— Anonymous"],
  ["09:20","Nine twenty. The pigeons were on the roof again.","— Anonymous"],
  ["09:25","Nine twenty-five. He stretched and looked out.","— Anonymous"],
  ["09:30","Half past nine. The morning was half spent.","— Anonymous"],
  ["09:35","Nine thirty-five. She found the number she was looking for.","— Anonymous"],
  ["09:40","Twenty to ten. He rewrote the paragraph.","— Anonymous"],
  ["09:45","A quarter to ten. The light changed.","— Anonymous"],
  ["09:50","Ten to ten. She sent the reply.","— Anonymous"],
  ["09:55","Five to ten. Almost time for the meeting.","— Anonymous"],
  ["10:00","Ten o'clock precisely. She put on her coat.","— Anonymous"],
  ["10:05","Five past ten. The meeting had already started.","— Anonymous"],
  ["10:10","Ten past ten. He found a seat near the door.","— Anonymous"],
  ["10:15","A quarter past ten. Notes were being taken.","— Anonymous"],
  ["10:20","Ten twenty. She disagreed but said nothing.","— Anonymous"],
  ["10:25","Ten twenty-five. The agenda moved on.","— Anonymous"],
  ["10:30","Half past ten. The morning was bright.","— Anonymous"],
  ["10:35","Ten thirty-five. Outside, a truck was reversing.","— Anonymous"],
  ["10:40","Twenty to eleven. He thought of other things.","— Anonymous"],
  ["10:45","A quarter to eleven. Almost done.","— Anonymous"],
  ["10:50","Ten to eleven. She underlined the key point.","— Anonymous"],
  ["10:55","Five to eleven. It was nearly over.","— Anonymous"],
  ["11:00","Eleven o'clock. Time for a walk.","— Anonymous"],
  ["11:05","Five past eleven. The park was nearly empty.","— Anonymous"],
  ["11:10","Eleven ten. A dog ran across the path.","— Anonymous"],
  ["11:15","A quarter past eleven. Clouds came over.","— Anonymous"],
  ["11:20","Eleven twenty. He bought a sandwich early.","— Anonymous"],
  ["11:25","Eleven twenty-five. She looked up at the sky.","— Anonymous"],
  ["11:30","Half past eleven. Nearly noon.","— Anonymous"],
  ["11:35","Eleven thirty-five. She was almost ready.","— Anonymous"],
  ["11:40","Twenty to noon. He cleared the desk.","— Anonymous"],
  ["11:45","A quarter to noon. The smell of lunch.","— Anonymous"],
  ["11:50","Ten to noon. She finished the last line.","— Anonymous"],
  ["11:55","Five to noon. Almost time.","— Anonymous"],
  ["12:00","It was noon exactly when she finally understood.","— Anonymous"],
  ["12:05","Five past twelve. The sun was at its peak.","— Anonymous"],
  ["12:10","Twelve ten. He sat on the bench in the square.","— Anonymous"],
  ["12:15","A quarter past noon. The world paused to eat.","— Anonymous"],
  ["12:20","Twelve twenty. She watched the fountain.","— Anonymous"],
  ["12:25","Twelve twenty-five. Children ran past.","— Anonymous"],
  ["12:30","Half past noon. The afternoon lay ahead.","— Anonymous"],
  ["12:35","Twelve thirty-five. He folded the newspaper.","— Anonymous"],
  ["12:40","Twenty to one in the afternoon.","— Anonymous"],
  ["12:45","A quarter to one. She was beginning to feel the heat.","— Anonymous"],
  ["12:50","Ten to one. The restaurant filled up.","— Anonymous"],
  ["12:55","Five to one. They were already saving tables.","— Anonymous"],
  ["13:00","One o'clock. The afternoon had quietly begun.","— Anonymous"],
  ["13:05","Five past one in the afternoon.","— Anonymous"],
  ["13:10","One ten. He found a shaded seat.","— Anonymous"],
  ["13:15","A quarter past one. The world felt unhurried.","— Anonymous"],
  ["13:20","One twenty. The pigeons had found the crumbs.","— Anonymous"],
  ["13:25","One twenty-five. She read a page or two.","— Anonymous"],
  ["13:30","Half past one. The work waited patiently.","— Anonymous"],
  ["13:35","One thirty-five. He stretched his legs.","— Anonymous"],
  ["13:40","Twenty to two in the afternoon.","— Anonymous"],
  ["13:45","A quarter to two. She thought about the morning.","— Anonymous"],
  ["13:50","Ten to two. Back to the desk soon.","— Anonymous"],
  ["13:55","Five to two. One last look at the sky.","— Anonymous"],
  ["14:00","Two o'clock in the afternoon.","— Anonymous"],
  ["14:05","Five past two. The afternoon settled in.","— Anonymous"],
  ["14:10","Two ten. He found his rhythm at last.","— Anonymous"],
  ["14:15","A quarter past two. She was making progress.","— Anonymous"],
  ["14:20","Two twenty. The afternoon light was warm.","— Anonymous"],
  ["14:25","Two twenty-five. A fly landed on the window.","— Anonymous"],
  ["14:30","Half past two. The afternoon was in full swing.","— Anonymous"],
  ["14:35","Two thirty-five. He read the paragraph again.","— Anonymous"],
  ["14:40","Twenty to three. She was nearly there.","— Anonymous"],
  ["14:45","A quarter to three. Almost time for tea.","— Anonymous"],
  ["14:50","Ten to three. The kettle was already on.","— Anonymous"],
  ["14:55","Five to three. She was nearly there.","— Anonymous"],
  ["15:00","Three o'clock in the afternoon. The day's third act.","— Anonymous"],
  ["15:05","Five past three. The afternoon slumped slightly.","— Anonymous"],
  ["15:10","Three ten. Coffee helped.","— Anonymous"],
  ["15:15","A quarter past three.","— Anonymous"],
  ["15:20","Three twenty. The birds were restless in the trees.","— Anonymous"],
  ["15:25","Three twenty-five. He allowed himself a biscuit.","— Anonymous"],
  ["15:30","Half past three. The day was more than half done.","— Anonymous"],
  ["15:35","Three thirty-five. She resolved to finish before dark.","— Anonymous"],
  ["15:40","Twenty to four in the afternoon.","— Anonymous"],
  ["15:45","A quarter to four. The light was golden.","— Anonymous"],
  ["15:50","Ten to four. She was almost finished.","— Anonymous"],
  ["15:55","Five to four. The end was in sight.","— Anonymous"],
  ["16:00","Four o'clock in the afternoon.","— Anonymous"],
  ["16:05","Five past four. She stretched at last.","— Anonymous"],
  ["16:10","Four ten. He saved the document.","— Anonymous"],
  ["16:15","A quarter past four.","— Anonymous"],
  ["16:20","Four twenty. The shadows were lengthening.","— Anonymous"],
  ["16:25","Four twenty-five. She began to tidy the desk.","— Anonymous"],
  ["16:30","Half past four. The afternoon was winding down.","— Anonymous"],
  ["16:35","Four thirty-five. The street was quieter.","— Anonymous"],
  ["16:40","Twenty to five in the afternoon.","— Anonymous"],
  ["16:45","A quarter to five. Nearly the end of the working day.","— Anonymous"],
  ["16:50","Ten to five. One last thing.","— Anonymous"],
  ["16:55","Five to five. She saved everything twice.","— Anonymous"],
  ["17:00","Five o'clock. Done for the day.","— Anonymous"],
  ["17:05","Five past five in the evening.","— Anonymous"],
  ["17:10","Five ten. He locked the office door.","— Anonymous"],
  ["17:15","A quarter past five in the evening.","— Anonymous"],
  ["17:20","Five twenty. The evening was beginning.","— Anonymous"],
  ["17:25","Five twenty-five. She walked slowly home.","— Anonymous"],
  ["17:30","Half past five. The sun was lower now.","— Anonymous"],
  ["17:35","Five thirty-five. The first stars were invisible yet.","— Anonymous"],
  ["17:40","Twenty to six. He cooked something simple.","— Anonymous"],
  ["17:45","A quarter to six in the evening.","— Anonymous"],
  ["17:50","Ten to six. She opened a book.","— Anonymous"],
  ["17:55","Five to six. The evening was her own.","— Anonymous"],
  ["18:00","Six o'clock in the evening.","— Anonymous"],
  ["18:05","Five past six. She poured a glass.","— Anonymous"],
  ["18:10","Six ten. The news was the same as always.","— Anonymous"],
  ["18:15","A quarter past six. She turned it off.","— Anonymous"],
  ["18:20","Six twenty. He telephoned a friend.","— Anonymous"],
  ["18:25","Six twenty-five. Laughter on the line.","— Anonymous"],
  ["18:30","Half past six. The day was nearly done.","— Anonymous"],
  ["18:35","Six thirty-five. She walked to the window.","— Anonymous"],
  ["18:40","Twenty to seven in the evening.","— Anonymous"],
  ["18:45","A quarter to seven. Dinner was ready.","— Anonymous"],
  ["18:50","Ten to seven. He set the table.","— Anonymous"],
  ["18:55","Five to seven. The evening light was beautiful.","— Anonymous"],
  ["19:00","Seven o'clock in the evening.","— Anonymous"],
  ["19:05","Five past seven. She read the old letters.","— Anonymous"],
  ["19:10","Seven ten. The room was warm.","— Anonymous"],
  ["19:15","A quarter past seven in the evening.","— Anonymous"],
  ["19:20","Seven twenty. He built a fire.","— Anonymous"],
  ["19:25","Seven twenty-five. The evening settled in.","— Anonymous"],
  ["19:30","Half past seven. She returned to her book.","— Anonymous"],
  ["19:35","Seven thirty-five. The chapter was long but good.","— Anonymous"],
  ["19:40","Twenty to eight in the evening.","— Anonymous"],
  ["19:45","A quarter to eight. He made notes in the margin.","— Anonymous"],
  ["19:50","Ten to eight. The fire crackled.","— Anonymous"],
  ["19:55","Five to eight. One more chapter.","— Anonymous"],
  ["20:00","Eight o'clock in the evening.","— Anonymous"],
  ["20:05","Five past eight. The children were in bed.","— Anonymous"],
  ["20:10","Eight ten. The house was peaceable.","— Anonymous"],
  ["20:15","A quarter past eight in the evening.","— Anonymous"],
  ["20:20","Eight twenty. She wrote in her journal.","— Anonymous"],
  ["20:25","Eight twenty-five. The pen moved easily.","— Anonymous"],
  ["20:30","Half past eight. She had written two pages.","— Anonymous"],
  ["20:35","Eight thirty-five. He closed the book and thought.","— Anonymous"],
  ["20:40","Twenty to nine in the evening.","— Anonymous"],
  ["20:45","A quarter to nine. The night was calm.","— Anonymous"],
  ["20:50","Ten to nine. He put another log on.","— Anonymous"],
  ["20:55","Five to nine. The evening was perfectly quiet.","— Anonymous"],
  ["21:00","Nine o'clock. The day was all but done.","— Anonymous"],
  ["21:05","Five past nine. The stars were clear tonight.","— Anonymous"],
  ["21:10","Nine ten. She looked out at the garden.","— Anonymous"],
  ["21:15","A quarter past nine. He poured a nightcap.","— Anonymous"],
  ["21:20","Nine twenty. The streets were nearly empty.","— Anonymous"],
  ["21:25","Nine twenty-five. She answered the last message.","— Anonymous"],
  ["21:30","Half past nine. The world was winding down.","— Anonymous"],
  ["21:35","Nine thirty-five. He set the clock.","— Anonymous"],
  ["21:40","Twenty to ten in the evening.","— Anonymous"],
  ["21:45","A quarter to ten. Nearly time for bed.","— Anonymous"],
  ["21:50","Ten to ten. She closed the laptop.","— Anonymous"],
  ["21:55","Five to ten. The house fell quiet.","— Anonymous"],
  ["22:00","Ten o'clock. The evening ended.","— Anonymous"],
  ["22:05","Five past ten. He brushed his teeth.","— Anonymous"],
  ["22:10","Ten past ten. She turned out the kitchen light.","— Anonymous"],
  ["22:15","A quarter past ten. Almost ready for sleep.","— Anonymous"],
  ["22:20","Ten twenty. He read one more paragraph.","— Anonymous"],
  ["22:25","Ten twenty-five. Sleep was close.","— Anonymous"],
  ["22:30","Half past ten. The room was dark.","— Anonymous"],
  ["22:35","Ten thirty-five. He could hear the rain.","— Anonymous"],
  ["22:40","Twenty to eleven. Almost asleep.","— Anonymous"],
  ["22:45","A quarter to eleven at night.","— Anonymous"],
  ["22:50","Ten to eleven. She thought about tomorrow.","— Anonymous"],
  ["22:55","Five to eleven. The last light in the street.","— Anonymous"],
  ["23:00","Eleven o'clock at night. The house was still.","— Anonymous"],
  ["23:05","Five past eleven. He turned the page.","— Anonymous"],
  ["23:10","Eleven ten. She would finish the chapter.","— Anonymous"],
  ["23:15","A quarter past eleven. Not quite midnight.","— Anonymous"],
  ["23:20","Eleven twenty. The wind moved in the trees.","— Anonymous"],
  ["23:25","Eleven twenty-five. One last thing.","— Anonymous"],
  ["23:30","Half past eleven. Tomorrow was already close.","— Anonymous"],
  ["23:35","Eleven thirty-five. She set her alarm.","— Anonymous"],
  ["23:40","Twenty to midnight. He lay in the dark.","— Anonymous"],
  ["23:45","A quarter to midnight. Sleep came slowly.","— Anonymous"],
  ["23:50","Ten to midnight. Almost the end of the day.","— Anonymous"],
  ["23:55","Five to midnight. One last breath of the evening.","— Anonymous"],
];

export const LIT_CLOCK: LitClock = Object.fromEntries(
  RAW.map(([key, quote, source]) => [key, { quote, source }])
);
